"""Type stub for the native typani_core extension module (T-0010).

Mirrors src/typani/result.py and src/typani/option.py signatures exactly
so type checkers see the same surface under either backend.
"""

from typing import Any, Callable, Generic, Iterator, TypeVar

T_co = TypeVar("T_co", covariant=True)
E_co = TypeVar("E_co", covariant=True)
U = TypeVar("U")
V = TypeVar("V")
F = TypeVar("F")
E = TypeVar("E")

__version__: str

class Result(Generic[T_co, E_co]):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @classmethod
    def catch(
        cls,
        fn: Callable[[], T_co],
        *exceptions: type[BaseException],
        on_error: Callable[[BaseException], E_co],
    ) -> "Result[T_co, E_co]": ...
    @property
    def is_ok(self) -> bool: ...
    @property
    def is_err(self) -> bool: ...
    @property
    def ok(self) -> T_co | None: ...
    @property
    def err(self) -> E_co | None: ...
    @property
    def danger_ok(self) -> T_co: ...
    @property
    def danger_err(self) -> E_co: ...
    @property
    def notes(self) -> tuple[str, ...]: ...
    @property
    def trace(self) -> tuple[str, ...]: ...
    def is_ok_and(self, pred: Callable[[T_co], bool]) -> bool: ...
    def is_err_and(self, pred: Callable[[E_co], bool]) -> bool: ...
    def unwrap(self, *, err: F | None = None, note: str | None = None) -> T_co: ...
    def unwrap_err(self) -> E_co: ...
    def unwrap_or(self, default: U) -> T_co | U: ...
    def unwrap_or_else(self, fn: Callable[[E_co], U]) -> T_co | U: ...
    def expect(self, msg: str) -> T_co: ...
    def expect_err(self, msg: str) -> E_co: ...
    def map(self, fn: Callable[[T_co], V]) -> "Result[V, E_co]": ...
    def map_err(self, fn: Callable[[E_co], F]) -> "Result[T_co, F]": ...
    def and_then(self, fn: Callable[[T_co], "Result[V, F]"]) -> "Result[V, Any]": ...
    def or_else(self, fn: Callable[[E_co], "Result[T_co, F]"]) -> "Result[T_co, F]": ...
    def inspect(self, fn: Callable[[T_co], None]) -> "Result[T_co, E_co]": ...
    def inspect_err(self, fn: Callable[[E_co], None]) -> "Result[T_co, E_co]": ...
    def fold(self, on_ok: Callable[[T_co], U], on_err: Callable[[E_co], U]) -> U: ...
    def to_option(self) -> Any: ...
    def note(self, msg: str) -> "Result[T_co, E_co]": ...
    def wrap_err(self, err: F) -> "Result[T_co, F]": ...
    def traced(self, site: str) -> "Result[T_co, E_co]": ...
    def swap_err(self, err: type[F]) -> "Result[T_co, F]": ...
    def swap_ok(self, ok: type[V]) -> "Result[V, E_co]": ...
    def __or__(self, fn: Callable[[T_co], V]) -> "Result[V, E_co]": ...
    def __rshift__(self, fn: Callable[[T_co], "Result[V, F]"]) -> "Result[V, Any]": ...
    def __iter__(self) -> Iterator[T_co]: ...
    def __bool__(self) -> bool: ...
    def __copy__(self) -> "Result[T_co, E_co]": ...
    def __deepcopy__(self, memo: dict[int, object]) -> "Result[T_co, E_co]": ...

class Ok(Result[T_co, E_co]):
    __match_args__: tuple[str, ...]
    def __init__(self, value: T_co, /) -> None: ...
    @property
    def value(self) -> T_co: ...

class Err(Result[T_co, E_co]):
    __match_args__: tuple[str, ...]
    def __init__(self, error: E_co, /) -> None: ...
    @property
    def error(self) -> E_co: ...

def _rebuild_err(error: Any, notes: tuple[str, ...]) -> Err[Any, Any]: ...

class Option(Generic[T_co]):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @classmethod
    def from_optional(cls, x: U | None) -> "Option[U]": ...
    @property
    def is_some(self) -> bool: ...
    @property
    def is_nothing(self) -> bool: ...
    @property
    def some(self) -> T_co | None: ...
    @property
    def danger_some(self) -> T_co: ...
    def unwrap(self, *, err: E | None = None, note: str | None = None) -> T_co: ...
    def unwrap_or(self, default: U) -> T_co | U: ...
    def unwrap_or_else(self, fn: Callable[[], U]) -> T_co | U: ...
    def expect(self, msg: str) -> T_co: ...
    def map(self, fn: Callable[[T_co], V]) -> "Option[V]": ...
    def and_then(self, fn: Callable[[T_co], "Option[V]"]) -> "Option[V]": ...
    def or_else(self, fn: Callable[[], "Option[U]"]) -> "Option[T_co | U]": ...
    def inspect(self, fn: Callable[[T_co], None]) -> "Option[T_co]": ...
    def filter(self, pred: Callable[[T_co], bool]) -> "Option[T_co]": ...
    def ok_or(self, err: E) -> Result[T_co, E]: ...
    def ok_or_else(self, fn: Callable[[], E]) -> Result[T_co, E]: ...
    def __or__(self, fn: Callable[[T_co], V]) -> "Option[V]": ...
    def __rshift__(self, fn: Callable[[T_co], "Option[V]"]) -> "Option[V]": ...
    def __iter__(self) -> Iterator[T_co]: ...
    def __bool__(self) -> bool: ...
    def __copy__(self) -> "Option[T_co]": ...
    def __deepcopy__(self, memo: dict[int, object]) -> "Option[T_co]": ...

class Some(Option[T_co]):
    __match_args__: tuple[str, ...]
    def __init__(self, value: T_co, /) -> None: ...
    @property
    def value(self) -> T_co: ...

class Nothing(Option[Any]):
    __match_args__: tuple[str, ...]
    def __init__(self, *args: object, **kwargs: object) -> None: ...
